# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["yusuke@kamawada.com"]
description = "A starter template with Hono for the Fastly Compute@Edge."
language = "javascript"
manifest_version = 2
name = "vcl-to-compute"
service_id = ""
